from __future__ import annotations

from enum import StrEnum


class Role(StrEnum):
    ADMINISTRATOR = "Administrator"
    OPERATOR = "Operator"
    REVIEWER = "Reviewer"
    VIEWER = "Viewer"


# Aviation personas map onto session roles + fine-grained permissions (see docs/RBAC.md).
AVIATION_PERSONAS = (
    "technician",
    "store",
    "planner",
    "inspector",
    "aca",
    "engineering",
    "reliability",
    "qa",
    "purchasing",
    "finance",
    "supervisor",
    "manager",
    "administrator",
)

PERMISSIONS_BY_ROLE: dict[Role, set[str]] = {
    Role.ADMINISTRATOR: {"*"},
    Role.OPERATOR: {
        "incident.create",
        "incident.update",
        "incident.event",
        "incident.evidence",
        "incident.read",
        "approval.request",
        "alerts.ack",
        "alerts.read",
        "reports.read",
        "connectors.read",
        "connectors.manage",
        "decisions.read",
        "decisions.review",
        "dashboard.read",
        "platform.read",
        "ops.read",
        "ops.coordinate",
        "org.read",
        "fleet.read",
        "fleet.manage",
        "component.read",
        "component.manage",
        "configuration.read",
        "configuration.manage",
        "publication.read",
        "publication.manage",
        "personnel.read",
        "personnel.manage",
        "maintenance.read",
        "maintenance.manage",
        "certification.sign",
        "logbook.read",
        "signature.create",
        "task.read",
        "task.manage",
        "work_order.read",
        "work_order.manage",
        "work_order.execute",
        "store.read",
        "planner.read",
        "planning.read",
        "planning.manage",
        "logistics.read",
        "logistics.manage",
        "logistics.stores",
        "logistics.purchase",
        "logistics.tools",
        "logistics.finance",
        "platform.manage",
        "marketplace.read",
        "marketplace.manage",
        "oem.read",
        "authority.read",
        "fabric.read",
        "fabric.manage",
        "ecosystem.read",
        "ecosystem.manage",
        "connect.read",
        "connect.manage",
        "network.read",
        "network.manage",
        "twin.read",
        "twin.manage",
        "plugins.read",
        "plugins.manage",
        "event_fabric.read",
        "event_fabric.manage",
    },
    Role.REVIEWER: {
        "approval.review",
        "alerts.ack",
        "alerts.read",
        "audit.read",
        "reports.read",
        "connectors.read",
        "decisions.read",
        "decisions.review",
        "incident.read",
        "dashboard.read",
        "platform.read",
        "org.read",
        "fleet.read",
        "component.read",
        "configuration.read",
        "publication.read",
        "personnel.read",
        "maintenance.read",
        "certification.sign",
        "certification.release",
        "logbook.read",
        "signature.create",
        "task.read",
        "work_order.read",
        "work_order.execute",
        "inspector.approve",
        "engineering.read",
        "qa.read",
        "planning.read",
        "logistics.read",
        "logistics.tools",
        "marketplace.read",
        "oem.read",
        "authority.read",
        "fabric.read",
        "ecosystem.read",
        "connect.read",
        "network.read",
        "twin.read",
        "plugins.read",
        "event_fabric.read",
    },
    Role.VIEWER: {
        "reports.read",
        "connectors.read",
        "decisions.read",
        "incident.read",
        "alerts.read",
        "dashboard.read",
        "platform.read",
        "org.read",
        "fleet.read",
        "component.read",
        "configuration.read",
        "publication.read",
        "personnel.read",
        "maintenance.read",
        "logbook.read",
        "task.read",
        "work_order.read",
        "store.read",
        "planner.read",
        "planning.read",
        "engineering.read",
        "logistics.read",
        "marketplace.read",
        "oem.read",
        "authority.read",
        "fabric.read",
        "ecosystem.read",
        "connect.read",
        "network.read",
        "twin.read",
        "plugins.read",
        "event_fabric.read",
    },
}

# Persona → recommended permissions (documentation + future override engine).
PERSONA_PERMISSIONS: dict[str, set[str]] = {
    "technician": {
        "publication.read",
        "component.read",
        "configuration.read",
        "fleet.read",
        "task.read",
        "task.manage",
        "maintenance.read",
        "maintenance.manage",
        "work_order.read",
        "work_order.execute",
        "certification.sign",
        "signature.create",
        "logbook.read",
        "logistics.read",
    },
    "store": {
        "publication.read",
        "component.read",
        "store.read",
        "fleet.read",
        "work_order.read",
        "logistics.read",
        "logistics.stores",
        "logistics.tools",
    },
    "planner": {
        "publication.read",
        "planner.read",
        "planning.read",
        "planning.manage",
        "fleet.read",
        "maintenance.read",
        "task.read",
        "work_order.read",
        "work_order.manage",
        "logistics.read",
    },
    "supervisor": {
        "publication.read",
        "fleet.read",
        "maintenance.read",
        "work_order.read",
        "work_order.manage",
        "logistics.read",
        "logistics.manage",
        "logistics.stores",
    },
    "manager": {
        "publication.read",
        "fleet.read",
        "planning.read",
        "work_order.read",
        "logistics.read",
        "logistics.manage",
        "logistics.purchase",
        "logistics.finance",
    },
    "purchasing": {
        "publication.read",
        "fleet.read",
        "logistics.read",
        "logistics.purchase",
    },
    "finance": {
        "publication.read",
        "logistics.read",
        "logistics.finance",
        "logistics.purchase",
    },
    "maintenance_control": {
        "planning.read",
        "planning.manage",
        "fleet.read",
        "maintenance.read",
        "work_order.read",
        "work_order.manage",
        "publication.read",
    },
    "inspector": {
        "publication.read",
        "maintenance.read",
        "certification.sign",
        "inspector.approve",
        "signature.create",
        "logbook.read",
        "audit.read",
        "task.read",
        "work_order.read",
        "work_order.execute",
    },
    "aca": {
        "publication.read",
        "certification.sign",
        "certification.release",
        "signature.create",
        "logbook.read",
        "maintenance.read",
        "task.read",
        "work_order.read",
        "work_order.execute",
    },
    "engineering": {
        "publication.read",
        "engineering.read",
        "configuration.read",
        "component.read",
        "fleet.read",
        "logistics.read",
    },
    "reliability": {"publication.read", "fleet.read", "component.read", "maintenance.read", "qa.read", "logistics.read"},
    "qa": {
        "qa.read",
        "audit.read",
        "publication.read",
        "maintenance.read",
        "logbook.read",
        "certification.sign",
        "logistics.read",
    },
    "administrator": {"*"},
}


def parse_role(value: str | None) -> Role:
    if not value:
        return Role.VIEWER
    normalized = value.strip().lower()
    for role in Role:
        if role.value.lower() == normalized:
            return role
    return Role.VIEWER


def has_permissions(role_value: str | None, required: tuple[str, ...]) -> bool:
    role = parse_role(role_value)
    granted = PERMISSIONS_BY_ROLE.get(role, set())
    if "*" in granted:
        return True
    return all(permission in granted for permission in required)


def persona_permissions(persona: str | None) -> set[str]:
    if not persona:
        return set()
    return set(PERSONA_PERMISSIONS.get(persona.strip().lower(), set()))
