"""Canonical entity-type catalog for the Universal Entity Model."""

from __future__ import annotations

# (code, name, domain, passport_kind, description)
ENTITY_TYPE_CATALOG: list[tuple[str, str, str, str, str]] = [
    ("organization", "Organization", "platform", "organization", "Tenant organization"),
    ("facility", "Facility", "platform", "organization", "Hangar / shop / station"),
    ("personnel", "Personnel", "platform", "personnel", "Employee / technician"),
    ("aircraft", "Aircraft", "aviation", "aircraft", "Registered aircraft"),
    ("fleet", "Fleet", "aviation", "aircraft", "Fleet grouping"),
    ("aircraft_configuration", "Aircraft Configuration", "aviation", "aircraft", "As-installed config"),
    ("component", "Component", "aviation", "component", "Catalog / serialized component"),
    ("serialized_component", "Serialized Component", "aviation", "component", "Tracked serial unit"),
    ("publication", "Publication", "aviation", "publication", "Technical publication"),
    ("maintenance_task", "Maintenance Task", "aviation", "aircraft", "Task engine record"),
    ("work_order", "Work Order", "aviation", "aircraft", "Work order"),
    ("job_card", "Job Card", "aviation", "aircraft", "Job card execution"),
    ("task_card", "Task Card", "aviation", "aircraft", "Task card"),
    ("finding", "Finding", "aviation", "aircraft", "Inspection finding"),
    ("defect", "Defect", "aviation", "aircraft", "Deferred / open defect"),
    ("engineering_order", "Engineering Order", "aviation", "publication", "EO"),
    ("service_bulletin", "Service Bulletin", "aviation", "publication", "SB"),
    ("airworthiness_directive", "Airworthiness Directive", "aviation", "publication", "AD"),
    ("reliability", "Reliability Record", "aviation", "aircraft", "Reliability metric"),
    ("inventory_part", "Inventory Part", "logistics", "component", "Part master / stock"),
    ("purchase_order", "Purchase Order", "logistics", "organization", "PO"),
    ("supplier", "Supplier", "logistics", "organization", "Vendor / supplier"),
    ("repair_station", "Repair Station", "logistics", "organization", "Repair station"),
    ("calibration", "Calibration Record", "logistics", "tool", "Calibration event"),
    ("tool", "Tool", "logistics", "tool", "Tool crib asset"),
    ("gse", "Ground Support Equipment", "logistics", "tool", "GSE"),
    ("training", "Training Record", "platform", "personnel", "Training"),
    ("certificate", "Certificate", "platform", "personnel", "Certificate"),
    ("authorization", "Authorization", "platform", "personnel", "ACA / authorization"),
    ("release_certificate", "Release Certificate", "aviation", "aircraft", "CRS / release"),
    ("digital_logbook", "Digital Logbook Entry", "aviation", "aircraft", "Tech log entry"),
    ("customer", "Customer", "platform", "organization", "Customer account"),
    ("project", "Project", "platform", "organization", "Project / visit"),
    ("marketplace_listing", "Marketplace Listing", "marketplace", "organization", "Marketplace listing"),
    ("marketplace_seller", "Marketplace Seller", "marketplace", "organization", "Seller digital profile"),
    ("marketplace_product", "Marketplace Product", "marketplace", "organization", "Catalog product or service"),
    ("marketplace_order", "Marketplace Order", "marketplace", "organization", "Purchase order"),
    ("marketplace_quote", "Marketplace Quote", "marketplace", "organization", "Digital quote / RFQ"),
    ("network_org_profile", "Network Org Profile", "network", "organization", "Aviation Network org profile"),
    ("network_professional", "Network Professional", "network", "personnel", "Professional network profile"),
    ("network_partnership", "Network Partnership", "network", "organization", "Explicit cross-org partnership"),
    ("network_collaboration", "Network Collaboration", "network", "organization", "Authorized collaboration"),
    ("digital_twin", "Digital Twin", "twin", "aircraft", "Digital Twin lifecycle object"),
    ("twin_configuration", "Twin Configuration", "twin", "aircraft", "Configuration baseline"),
    ("career_profile", "Career Profile", "marketplace", "personnel", "Careers profile"),
    ("academy_course", "Academy Course", "marketplace", "publication", "Academy course"),
    ("authority_audit", "Authority Audit", "authority", "organization", "Oversight audit record"),
]

RELATIONSHIP_TYPES = (
    "configured_as",
    "installed_on",
    "removed_from",
    "performed_on",
    "assigned_to",
    "inspected_by",
    "finding_of",
    "supersedes",
    "references",
    "related_to",
    "owned_by",
    "part_of",
    "derived_from",
    "approves",
    "releases",
)

EVENT_TYPES = (
    "created",
    "updated",
    "installed",
    "removed",
    "released",
    "signed",
    "approved",
    "rejected",
    "transferred",
    "calibrated",
    "inspected",
    "published",
    "archived",
    "cancelled",
    "deleted",
)
