import { state } from "./state.js";
import { el, esc, toast } from "./utils.js";
import { updateWeather, updateProactiveBrief } from "./missionOps.js";
import { updateCommandCenter, pushNotification } from "./commandCenter.js";
import { updateRealtimeConsole } from "./realtimeConsole.js";
const labels=["RF track updated","Radar plot correlated","EO camera maintained lock","Thermal signature confirmed","Predicted path recalculated","Runway conflict window updated","Secondary UAV track detected","Aircraft deconfliction recalculated"];
export function updateFusion(step=0){const jitter=(base,n)=>Math.max(55,Math.min(100,base+Math.round(Math.sin((step+n)*.8)*4)));state.fusion={rf:jitter(92,0),radar:jitter(84,1),eo:jitter(97,2),thermal:jitter(88,3),adsb:100};const fused=Math.round(state.fusion.rf*.25+state.fusion.radar*.2+state.fusion.eo*.3+state.fusion.thermal*.15+10);state.dynamicThreat=Math.max(62,Math.min(99,Math.round(fused-8+step*2.8)));el("fusionBars").innerHTML=Object.entries(state.fusion).map(([k,v])=>`<div class="fusion-row"><span>${esc(k.toUpperCase())}</span><div class="mini-bar"><i style="width:${v}%"></i></div><strong>${v}%</strong></div>`).join("")+`<div class="fusion-total"><span>FUSED CONFIDENCE</span><strong>${fused}%</strong></div>`;el("selectedConfidence").textContent=`${fused}%`;el("liveThreatScore").textContent=state.dynamicThreat;return fused}
export function appendLiveEvent(step){if(!state.selectedIncidentId)return;const text=labels[step%labels.length];state.liveEvents.unshift({text,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})});state.liveEvents=state.liveEvents.slice(0,8);el("liveTimeline").innerHTML=state.liveEvents.map((x,i)=>`<div class="live-event ${i===0?"latest":""}"><time>${esc(x.time)}</time><span>${esc(x.text)}</span></div>`).join("")}
export function updateThreatMatrix(){const a=state.selectedAssessment||{level:"HIGH"};const level=state.dynamicThreat>=90?"CRITICAL":a.level;el("threatMatrixBody").innerHTML=`<tr><td>UAV-01</td><td><span class="severity high">${esc(level)}</span></td><td>${esc(el("targetAltitude").textContent)}</td><td>${esc(el("targetSpeed").textContent)}</td><td>${esc(el("targetHeading").textContent)}</td><td>${esc(el("targetEta").textContent)}</td><td>Primary track</td></tr><tr><td>UAV-02</td><td><span class="severity medium">MEDIUM</span></td><td>86 m</td><td>24 km/h</td><td>278°</td><td>06:18</td><td>Correlation pending</td></tr>`}
function updateMissionClock(){if(!state.missionStarted)return;const sec=Math.floor((Date.now()-state.missionStarted)/1000);el("missionClock").textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`}
function criticalAlert(){if(state.dynamicThreat<90||state.criticalAlertShown)return;state.criticalAlertShown=true;el("criticalAlert").classList.remove("hidden");el("criticalAlertText").textContent=`UAV-01 threat score ${state.dynamicThreat}. Estimated runway arrival ${el("targetEta").textContent}.`;el("systemMode").textContent="CRITICAL RESPONSE";pushNotification("Critical airspace alert",`UAV-01 threat score ${state.dynamicThreat}; runway ETA ${el("targetEta").textContent}.`)}
export function onTrackingTick(step){updateFusion(step);appendLiveEvent(step);updateThreatMatrix();updateMissionClock();updateWeather(step);updateProactiveBrief(step);updateCommandCenter(step);updateRealtimeConsole(step);criticalAlert()}
export function acknowledgeThreat(){if(!state.selectedIncidentId)return toast("Select an incident first");el("ackStatus").textContent="ACKNOWLEDGED";el("ackStatus").classList.add("active");toast("Threat acknowledged by operator")}
