import { AIRPORTS, AIRPORT, UAV_TRACK, UAV_TRACK_2, SENSOR_SITES, AIRCRAFT_TRACKS } from "./config.js";
import { state } from "./state.js";
import { el } from "./utils.js";
const divIcon=(html,cls)=>L.divIcon({className:"",html:`<div class="${cls}">${html}</div>`,iconSize:[28,28],iconAnchor:[14,14]});
const shift=(track,center)=>{const da=center[0]-AIRPORT[0],db=center[1]-AIRPORT[1];return track.map(([a,b])=>[a+da,b+db])};
function buildOperationalLayers(center){
 state.zoneLayers=[L.circle(center,{radius:2300,color:"#22c55e",weight:1,fillOpacity:.02}),L.circle(center,{radius:1500,color:"#f59e0b",weight:2,fillOpacity:.035}),L.circle(center,{radius:800,color:"#ef4444",weight:2,fillColor:"#ef4444",fillOpacity:.05})]; state.zoneLayers.forEach(x=>x.addTo(state.map));
 state.sensorMarkers=SENSOR_SITES.map((s,i)=>{const da=center[0]-AIRPORT[0],db=center[1]-AIRPORT[1];return L.marker([s.position[0]+da,s.position[1]+db],{icon:divIcon(i%2?"●":"◆","sensor-icon")}).addTo(state.map).bindPopup(`<b>${s.id}</b><br>${s.type} sensor<br>Reliability ${s.reliability}%`) });
 const t1=shift(UAV_TRACK,center),t2=shift(UAV_TRACK_2,center); state.dronePath=[t1[0]]; state.secondaryPath=[t2[0]];
 state.trailLayer=L.polyline(t1,{color:"#ef4444",weight:3,dashArray:"7 7",opacity:.45}).addTo(state.map); state.secondaryTrail=L.polyline(t2,{color:"#f59e0b",weight:2,dashArray:"5 8",opacity:.35}).addTo(state.map);
 state.droneMarker=L.marker(t1[0],{icon:divIcon("⬥","drone-icon")}).addTo(state.map).bindPopup("<b>UAV-01</b><br>Primary unidentified target");
 state.secondaryDrone=L.marker(t2[0],{icon:divIcon("◆","drone-icon secondary")}).addTo(state.map).bindPopup("<b>UAV-02</b><br>Secondary low-confidence track");
 state.aircraftMarkers=AIRCRAFT_TRACKS.map((ac,i)=>{const pts=shift(ac.points,center);const marker=L.marker(pts[0],{icon:divIcon("✈","aircraft-icon")}).addTo(state.map).bindTooltip(`<span class="aircraft-label"><b>${ac.callsign}</b> · ${220+i*35} kt</span>`,{permanent:true,direction:"right",offset:[10,0],className:"aircraft-tooltip"});return {marker,points:pts,callsign:ac.callsign,index:i}});
}
export function initializeMap(){state.map=L.map("map").setView(AIRPORTS.CYUL.center,AIRPORTS.CYUL.zoom);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(state.map);L.marker(AIRPORTS.CYUL.center,{icon:divIcon("✈","airport-icon")}).addTo(state.map);buildOperationalLayers(AIRPORTS.CYUL.center);setTimeout(()=>state.map.invalidateSize(),150)}
function updateTelemetry(){const i=state.trackingIndex;el("targetAltitude").textContent=`${120+i*7} m`;el("targetSpeed").textContent=`${38+i*3} km/h`;el("targetHeading").textContent=`${(124+i*11)%360}°`;const seconds=Math.max(22,222-i*25);el("targetEta").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;el("replaySlider").value=Math.min(100,Math.round((i/(UAV_TRACK.length-1))*100));el("replayTime").textContent=`${String(Math.floor((222-seconds)/60)).padStart(2,"0")}:${String((222-seconds)%60).padStart(2,"0")} / 03:42`;}
function moveAircraft(){state.aircraftIndex++;state.aircraftMarkers.forEach((ac,i)=>ac.marker.setLatLng(ac.points[(state.aircraftIndex+i)%ac.points.length]))}
export function tickTracking(onTick){const ap=AIRPORTS[el("airportSelect")?.value||"CYUL"],t1=shift(UAV_TRACK,ap.center),t2=shift(UAV_TRACK_2,ap.center);state.trackingIndex=(state.trackingIndex+1)%t1.length;state.droneMarker.setLatLng(t1[state.trackingIndex]);state.secondaryDrone.setLatLng(t2[(state.trackingIndex+2)%t2.length]);state.dronePath.push(t1[state.trackingIndex]);state.secondaryPath.push(t2[(state.trackingIndex+2)%t2.length]);if(state.dronePath.length>18)state.dronePath.shift();if(state.secondaryPath.length>18)state.secondaryPath.shift();state.trailLayer.setLatLngs(state.dronePath);state.secondaryTrail.setLatLngs(state.secondaryPath);moveAircraft();updateTelemetry();onTick?.(state.trackingIndex)}
export function startTracking(onTick){if(state.trackingTimer)return;if(!state.missionStarted)state.missionStarted=Date.now();el("trackingButton").textContent="■ Stop";el("systemMode").textContent="LIVE TRACKING";state.trackingTimer=setInterval(()=>tickTracking(onTick),1200/state.simulationSpeed)}
export function pauseTracking(){if(state.trackingTimer){clearInterval(state.trackingTimer);state.trackingTimer=null}el("trackingButton").textContent="▶ Track";el("systemMode").textContent="PAUSED"}
export function resetTracking(){pauseTracking();state.trackingIndex=0;state.dronePath=[];state.secondaryPath=[];const ap=AIRPORTS[el("airportSelect")?.value||"CYUL"],a=shift(UAV_TRACK,ap.center)[0],b=shift(UAV_TRACK_2,ap.center)[0];state.droneMarker.setLatLng(a);state.secondaryDrone.setLatLng(b);state.trailLayer.setLatLngs([a]);state.secondaryTrail.setLatLngs([b]);state.missionStarted=null;el("missionClock").textContent="00:00";updateTelemetry()}
export function toggleTracking(onTick){state.trackingTimer?pauseTracking():startTracking(onTick)}
export function setSimulationSpeed(speed,onTick){const running=!!state.trackingTimer;pauseTracking();state.simulationSpeed=Number(speed)||1;if(running)startTracking(onTick)}
export function toggleLayer(name,visible){state.layersVisible[name]=visible;const apply=l=>visible?l.addTo(state.map):state.map.removeLayer(l);if(name==="zones")state.zoneLayers.forEach(apply);if(name==="sensors")state.sensorMarkers.forEach(apply);if(name==="aircraft")state.aircraftMarkers.forEach(x=>apply(x.marker));if(name==="trail"){apply(state.trailLayer);apply(state.secondaryTrail)}}
export function changeAirport(code){const ap=AIRPORTS[code];pauseTracking();[...state.zoneLayers,...state.sensorMarkers,state.trailLayer,state.secondaryTrail,state.droneMarker,state.secondaryDrone,...state.aircraftMarkers.map(x=>x.marker)].filter(Boolean).forEach(x=>state.map.removeLayer(x));state.map.setView(ap.center,ap.zoom);buildOperationalLayers(ap.center);el("airportName").textContent=`${code} · ${ap.name} · simulated operational picture`;resetTracking()}
export function seekReplay(percent,onTick){const ap=AIRPORTS[el("airportSelect")?.value||"CYUL"],t1=shift(UAV_TRACK,ap.center),t2=shift(UAV_TRACK_2,ap.center);state.trackingIndex=Math.min(t1.length-1,Math.round((Number(percent)/100)*(t1.length-1)));state.droneMarker.setLatLng(t1[state.trackingIndex]);state.secondaryDrone.setLatLng(t2[(state.trackingIndex+2)%t2.length]);updateTelemetry();onTick?.(state.trackingIndex)}
