"""Canonical ecosystem + capability catalog for Program 12."""

from __future__ import annotations

# (code, name, category, products, description)
ECOSYSTEMS: list[tuple[str, str, str, list[str], str]] = [
    (
        "airline",
        "Airlines",
        "operator",
        ["Mercury Airline", "Mercury MRO", "Mercury CAMO", "Mercury Executive"],
        "Scheduled airline fleet, maintenance, ops control, and finance",
    ),
    (
        "business_aviation",
        "Business Aviation",
        "operator",
        ["Mercury Airline", "Mercury MRO", "Mercury Careers"],
        "Operators, charter, corporate FD, fractional, VIP",
    ),
    (
        "mro",
        "MRO",
        "provider",
        ["Mercury MRO", "Mercury Marketplace", "Mercury Academy"],
        "Maintenance repair overhaul production and shops",
    ),
    (
        "camo",
        "CAMO",
        "provider",
        ["Mercury CAMO", "Mercury MRO"],
        "Continuing airworthiness management",
    ),
    (
        "oem",
        "OEM",
        "oem",
        ["Mercury OEM", "Mercury Marketplace", "Mercury Academy"],
        "Manufacturer portals, manuals, SB, warranty, support",
    ),
    (
        "supplier",
        "Suppliers",
        "provider",
        ["Mercury Marketplace", "Mercury Connect"],
        "Parts, tools, calibration, repair and training providers",
    ),
    (
        "repair_station",
        "Repair Stations",
        "provider",
        ["Mercury MRO", "Mercury Marketplace", "Mercury Authority"],
        "AMO profiles, ratings, quotes, repair tracking, certificates",
    ),
    (
        "authority",
        "Authorities",
        "authority",
        ["Mercury Authority"],
        "Oversight readiness only — no regulatory approval claimed",
    ),
    (
        "training",
        "Training",
        "talent",
        ["Mercury Academy", "Mercury Careers"],
        "Courses, type ratings, certificates, training history",
    ),
    (
        "careers",
        "Careers",
        "talent",
        ["Mercury Careers", "Mercury Academy"],
        "Professional profiles, licenses, recruitment, matching",
    ),
    (
        "marketplace",
        "Marketplace",
        "commerce",
        ["Mercury Marketplace", "Mercury Connect"],
        "Parts, tools, repairs, training, jobs, contracts",
    ),
]

# ecosystem_code -> list of (capability_code, name, domain_refs, fabric_types, readiness)
CAPABILITIES: dict[str, list[tuple[str, str, list[str], list[str], str]]] = {
    "airline": [
        ("fleet", "Fleet", ["fleet"], ["aircraft", "fleet"], "ready"),
        ("maintenance", "Maintenance", ["maintenance", "work_orders"], ["work_order", "job_card"], "ready"),
        ("engineering", "Engineering", ["planning"], ["engineering_order", "service_bulletin"], "ready"),
        ("planning", "Planning", ["planning"], ["maintenance_task"], "ready"),
        ("ops_control", "Operations Control", ["ops"], ["aircraft"], "partial"),
        ("dispatch", "Dispatch", ["ops"], ["aircraft"], "planned"),
        ("cabin", "Cabin", ["fleet"], ["aircraft"], "planned"),
        ("stores", "Stores", ["logistics"], ["inventory_part", "tool"], "ready"),
        ("finance", "Finance", ["platform"], ["organization"], "partial"),
        ("quality", "Quality", ["maintenance", "personnel"], ["certificate", "authorization"], "ready"),
        ("training", "Training", ["personnel"], ["training", "certificate"], "partial"),
    ],
    "business_aviation": [
        ("operators", "Operators", ["org", "fleet"], ["organization", "aircraft"], "ready"),
        ("charter", "Charter Companies", ["org", "fleet"], ["organization", "aircraft"], "partial"),
        ("corporate_fd", "Corporate Flight Departments", ["org", "fleet"], ["organization", "aircraft"], "partial"),
        ("fractional", "Fractional Operators", ["org", "fleet"], ["organization", "aircraft"], "planned"),
        ("vip", "VIP Operations", ["org", "fleet"], ["organization", "aircraft"], "planned"),
    ],
    "mro": [
        ("maintenance", "Maintenance", ["maintenance", "work_orders"], ["work_order", "job_card"], "ready"),
        ("planning", "Planning", ["planning"], ["maintenance_task"], "ready"),
        ("production", "Production", ["work_orders"], ["job_card", "task_card"], "ready"),
        ("structures", "Structures", ["maintenance"], ["finding", "defect"], "partial"),
        ("avionics", "Avionics", ["components", "maintenance"], ["component"], "partial"),
        ("engine_shop", "Engine Shop", ["components", "logistics"], ["component", "serialized_component"], "partial"),
        ("component_shop", "Component Shop", ["components", "logistics"], ["component"], "ready"),
        ("wheel_brake", "Wheel & Brake", ["components", "logistics"], ["component"], "partial"),
        ("ndt", "NDT", ["maintenance", "personnel"], ["finding", "certificate"], "planned"),
        ("calibration", "Calibration", ["logistics"], ["calibration", "tool"], "ready"),
        ("quality", "Quality", ["maintenance", "personnel"], ["certificate", "release_certificate"], "ready"),
        ("technical_records", "Technical Records", ["publications", "maintenance"], ["digital_logbook", "publication"], "ready"),
    ],
    "camo": [
        ("airworthiness", "Airworthiness", ["planning", "maintenance"], ["aircraft", "airworthiness_directive"], "ready"),
        ("amp", "AMP", ["planning"], ["maintenance_task"], "ready"),
        ("ad", "AD", ["planning"], ["airworthiness_directive"], "ready"),
        ("sb", "SB", ["planning"], ["service_bulletin"], "ready"),
        ("eo", "EO", ["planning"], ["engineering_order"], "ready"),
        ("reliability", "Reliability", ["planning"], ["reliability"], "partial"),
        ("forecasting", "Forecasting", ["planning"], ["maintenance_task"], "ready"),
        ("tech_pubs", "Technical Publications", ["publications"], ["publication"], "ready"),
        ("configuration", "Configuration", ["components", "fleet"], ["aircraft_configuration", "component"], "ready"),
    ],
    "oem": [
        ("manufacturer_portal", "Manufacturer Portal", ["oem"], ["organization"], "ready"),
        ("aircraft_models", "Aircraft Models", ["fleet", "oem"], ["aircraft"], "ready"),
        ("engines", "Engines", ["oem", "components"], ["component"], "ready"),
        ("apu", "APU", ["oem", "components"], ["component"], "ready"),
        ("components", "Components", ["oem", "components"], ["component"], "ready"),
        ("ipc", "IPC", ["publications", "oem"], ["publication"], "partial"),
        ("amm", "AMM", ["publications"], ["publication"], "ready"),
        ("wdm", "WDM", ["publications"], ["publication"], "planned"),
        ("fim", "FIM", ["publications"], ["publication"], "planned"),
        ("cmm", "CMM", ["publications"], ["publication"], "partial"),
        ("sb", "SB", ["planning", "oem"], ["service_bulletin"], "ready"),
        ("service_letters", "Service Letters", ["publications", "oem"], ["publication"], "partial"),
        ("warranty", "Warranty", ["oem", "marketplace"], ["marketplace_listing"], "planned"),
        ("training", "Training", ["oem"], ["academy_course", "training"], "partial"),
        ("support", "Support", ["oem", "connect"], ["organization"], "partial"),
        ("digital_manuals", "Digital Manuals", ["publications", "oem"], ["publication"], "ready"),
    ],
    "supplier": [
        ("parts", "Parts", ["logistics", "marketplace"], ["inventory_part", "marketplace_listing"], "ready"),
        ("consumables", "Consumables", ["logistics", "marketplace"], ["inventory_part"], "ready"),
        ("rotables", "Rotables", ["logistics"], ["serialized_component"], "ready"),
        ("expendables", "Expendables", ["logistics"], ["inventory_part"], "ready"),
        ("tools", "Tools", ["logistics", "marketplace"], ["tool"], "ready"),
        ("calibration", "Calibration", ["logistics"], ["calibration"], "ready"),
        ("repair_services", "Repair Services", ["marketplace"], ["repair_station", "marketplace_listing"], "partial"),
        ("engineering_services", "Engineering Services", ["marketplace"], ["marketplace_listing"], "planned"),
        ("training_providers", "Training Providers", ["marketplace"], ["academy_course"], "partial"),
        ("publications", "Publications", ["publications", "marketplace"], ["publication"], "ready"),
    ],
    "repair_station": [
        ("amo_profile", "AMO Profile", ["org", "authority"], ["organization", "repair_station"], "ready"),
        ("capabilities", "Capabilities", ["org"], ["repair_station"], "ready"),
        ("ratings", "Ratings", ["authority"], ["certificate"], "partial"),
        ("approvals", "Approvals", ["authority"], ["certificate", "authorization"], "partial"),
        ("turnaround", "Turnaround", ["logistics", "work_orders"], ["work_order"], "partial"),
        ("pricing", "Pricing", ["marketplace"], ["marketplace_listing"], "planned"),
        ("digital_quotes", "Digital Quotes", ["marketplace"], ["marketplace_listing"], "planned"),
        ("repair_tracking", "Repair Tracking", ["work_orders", "logistics"], ["work_order", "component"], "partial"),
        ("certificates", "Certificates", ["personnel", "maintenance"], ["certificate", "release_certificate"], "ready"),
    ],
    "authority": [
        ("transport_canada", "Transport Canada", ["authority"], ["authority_audit"], "ready"),
        ("faa", "FAA", ["authority"], ["authority_audit"], "ready"),
        ("easa", "EASA", ["authority"], ["authority_audit"], "ready"),
        ("caa_uk", "CAA UK", ["authority"], ["authority_audit"], "ready"),
        ("icao", "ICAO", ["authority"], ["authority_audit"], "ready"),
        ("other", "Other Authorities", ["authority"], ["authority_audit"], "ready"),
        ("audit", "Audit (future)", ["authority"], ["authority_audit"], "planned"),
        ("oversight", "Oversight (future)", ["authority"], ["authority_audit"], "planned"),
        ("certificate_verification", "Certificate Verification (future)", ["authority"], ["certificate"], "planned"),
        ("compliance", "Compliance (future)", ["authority"], ["authority_audit"], "planned"),
        ("digital_communication", "Digital Communication (future)", ["connect", "authority"], ["organization"], "planned"),
    ],
    "training": [
        ("organizations", "Training Organizations", ["org"], ["organization"], "ready"),
        ("courses", "Courses", ["marketplace"], ["academy_course"], "ready"),
        ("type_ratings", "Type Ratings", ["personnel"], ["training", "certificate"], "partial"),
        ("ewis", "EWIS", ["personnel"], ["training"], "planned"),
        ("human_factors", "Human Factors", ["personnel"], ["training"], "planned"),
        ("sms", "SMS", ["personnel"], ["training"], "planned"),
        ("ndt", "NDT Courses", ["personnel"], ["training", "certificate"], "planned"),
        ("engine_courses", "Engine Courses", ["personnel", "oem"], ["training"], "planned"),
        ("certificates", "Certificates", ["personnel"], ["certificate"], "ready"),
        ("training_history", "Training History", ["personnel"], ["training"], "partial"),
    ],
    "careers": [
        ("profiles", "Professional Profiles", ["personnel", "marketplace"], ["career_profile", "personnel"], "ready"),
        ("licenses", "Licenses", ["personnel"], ["certificate", "authorization"], "ready"),
        ("experience", "Experience", ["personnel"], ["personnel"], "partial"),
        ("skills", "Skills", ["personnel"], ["personnel"], "partial"),
        ("training", "Training", ["personnel"], ["training"], "partial"),
        ("employment", "Employment", ["personnel", "org"], ["personnel", "organization"], "planned"),
        ("recruitment", "Recruitment", ["marketplace"], ["career_profile"], "planned"),
        ("company_hiring", "Company Hiring", ["marketplace", "org"], ["career_profile"], "planned"),
        ("career_matching", "Career Matching", ["marketplace"], ["career_profile"], "planned"),
    ],
    "marketplace": [
        ("aircraft_parts", "Aircraft Parts", ["marketplace", "logistics"], ["marketplace_product", "inventory_part"], "ready"),
        ("tools", "Tools", ["marketplace", "logistics"], ["marketplace_product", "tool"], "ready"),
        ("test_equipment", "Test Equipment", ["marketplace"], ["marketplace_product", "tool"], "partial"),
        ("calibration", "Calibration", ["marketplace", "logistics"], ["marketplace_product", "calibration"], "ready"),
        ("repairs", "Repairs", ["marketplace"], ["marketplace_product", "marketplace_seller"], "ready"),
        ("engineering", "Engineering", ["marketplace"], ["marketplace_product"], "partial"),
        ("training", "Training", ["marketplace"], ["marketplace_product", "academy_course"], "ready"),
        ("jobs", "Jobs", ["marketplace"], ["marketplace_product", "career_profile"], "ready"),
        ("consulting", "Consulting", ["marketplace"], ["marketplace_product"], "partial"),
        ("reviews", "Marketplace Reviews", ["marketplace"], ["marketplace_seller", "marketplace_product"], "ready"),
        ("vendor_ratings", "Vendor Ratings", ["marketplace"], ["marketplace_seller"], "ready"),
        ("digital_quotes", "Digital Quotes", ["marketplace"], ["marketplace_quote"], "ready"),
        ("orders", "Orders", ["marketplace"], ["marketplace_order"], "ready"),
        ("digital_contracts", "Digital Contracts", ["marketplace"], ["marketplace_order"], "planned"),
    ],
}

# Mercury Connect connectors: (code, name, category, capabilities, readiness)
CONNECTORS: list[tuple[str, str, str, list[str], str]] = [
    ("erp.generic", "Generic ERP", "erp", ["master_data", "orders", "inventory"], "ready"),
    ("accounting.generic", "Generic Accounting", "accounting", ["invoices", "gl", "ap_ar"], "ready"),
    ("identity.oidc", "OIDC Identity Provider", "identity", ["sso", "logout"], "ready"),
    ("identity.azure_ad", "Azure AD", "identity", ["sso", "scim"], "ready"),
    ("identity.okta", "Okta", "identity", ["sso", "scim"], "ready"),
    ("identity.ldap", "LDAP", "identity", ["bind", "search"], "ready"),
    ("oem.portal", "OEM Systems Bridge", "oem", ["publications", "sb", "warranty"], "ready"),
    ("payment.generic", "Payment Gateway", "payment", ["charge", "refund"], "planned"),
    ("courier.generic", "Courier / Logistics Carrier", "courier", ["ship", "track"], "partial"),
    ("email.smtp", "Email (SMTP)", "email", ["send"], "ready"),
    ("sms.generic", "SMS Gateway", "sms", ["send"], "partial"),
    ("storage.object", "Document / Object Storage", "storage", ["put", "get", "version"], "ready"),
    ("weather.generic", "Weather Feed", "weather", ["metar", "taf"], "partial"),
    ("flight_ops.generic", "Flight Operations", "flight_ops", ["schedule", "status"], "planned"),
    ("efb.generic", "Electronic Flight Bag", "efb", ["docs", "sync"], "planned"),
    ("oem.garmin", "Garmin Aviation", "oem", ["flight_data", "avionics_sync", "efb_bridge"], "partial"),
    ("oem.honeywell", "Honeywell Aerospace", "oem", ["avionics_sync", "health_monitoring", "publications"], "partial"),
    ("inspection.drone", "Drone Inspection", "inspection", ["mission_plan", "imagery", "defect_markers"], "planned"),
    ("ndt.generic", "NDT Systems", "inspection", ["technique_catalog", "findings", "certificates"], "partial"),
    ("dashboard.custom", "Custom Dashboards", "analytics", ["widgets", "layouts", "kpis"], "ready"),
    ("safety.sms", "Safety Management System", "safety", ["hazards", "reports", "risk", "corrective_actions"], "planned"),
    ("fuel.planning", "Fuel Planning", "flight_ops", ["burn_estimate", "uplift", "cost_model"], "planned"),
]
